### PR TITLE
Add SDK and dependencies for new tracker

### PR DESCRIPTION
**Pull request by Tomcli**
We would like to have this journey also sent metrics to our new tracker to see its behavior.

- Add the new tracker SDK package, SDK call, and the metadata file(repository.yaml)
- Update tracker badge to our new tracker
- Update privacy notice

cc: @animeshsingh

### CODE REVIEW

**Comment by animeshsingh** [comment]
@ljbennett62 please get this pulled in

**Comment by ljbennett62** [comment]
@Tomcli @animeshsingh - it looks like this change breaks the build

**Comment by ljbennett62** [comment]
It looks like you are issuing the command "git clone -b master https://$GITHUB_USER:$GITHUB_PWD@github.com/IBM-Swift/Testing-Credentials.git" and it is failing because it should be IBM-Swift - it should be from the IBM org.

**Comment by Tomcli** [comment]
I think the build is failing because it's missing the credential from Travis environment variable. Since our branch is not in this repository, the PR build won't have access to `GITHUB_USER` and `GITHUB_PWD`.

Is it possible for you to create a new branch to test the build with this change?

**Comment by animeshsingh** [comment]
@Tomcli @ljbennett62 what`s holding this at this point - seems legit to me

**Comment by ljbennett62** [comment]
@animeshsingh @Tomcli - the build is failing because the problem is that because it is an external PR. Travis CI won't make the credentials available to the build job when building external PRs. 

We need to manually merge that PR locally on a macOS into a branch that one creates off master... and then push that branch to github. Then that build will run as usual and then one can do a PR from that branch into master.

**Comment by Tomcli** [comment]
Moved to #421

**Pull request closed without merging**
